### ISSUE TITLE
I don't get it.

### ISSUE THREAD

**Issue by zeke** [RichardLitt/a-bear#2]
:bear:

**Comment by tobbbles** [comment]
It's a difficult one to understand. Bear with, currently the core contributors are at polar opposites, and the direction this project is heading is apawling.

S'no problem to ask though.

**Comment by RichardLitt** [comment]
Hey @zeke!

It's not hard to get! To get the module on your system, you just need to run `npm install`. Put this in your command line (your terminal, if you're on a mac):

```
npm install a-bear
```

You should have it now. (:D)

**Comment by RichardLitt** [comment]
@mnzt I think you got it.

**Comment by zeke** [comment]
oso good
