### ISSUE TITLE
Not enough bears.

### ISSUE THREAD

**Issue by tobbbles** [RichardLitt/a-bear#3]
I really think we're lacking bear features.

I'd like to propose bear-unique branches, such as https://github.com/mnzt/a-bear/tree/exotic.

**Comment by RichardLitt** [comment]
PRs gladly accepted. :bear:

**Comment by tobbbles** [comment]
I'd love to put in a PR, I just can't create a new branch through a PR :cry: :bear:

**Comment by RichardLitt** [comment]
Hmm. I don't think branches are the way to go. I think options for the JS file would be the best way to do that.

**Comment by RichardLitt** [comment]
@mnzt Could you add an option to spit out different types of bear?

**Comment by tobbbles** [comment]
@RichardLitt On it. :sunglasses:

**Comment by RichardLitt** [comment]
.rar

**Comment by RichardLitt** [comment]
We now have more bears! Thanks!
